import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import Screen from "../../components/Screen";
import State from "../../components/State";
import ProgressSteps from "../../components/ProgressSteps";
import { useAuth } from "../../context/AuthContext";
import { supabase } from "../../lib/supabase";
import { ajouterJours, argent, isoAujourdHui, nombre, normaliser, texte } from "../../lib/format";

type Ligne={uid:string;prestation_id:string|null;designation:string;description:string;quantite:number;unite:string;prix_unitaire_ht:number;tva:number};
type Draft={step:number;client_id:string;objet:string;description:string;adresse_chantier:string;code_postal_chantier:string;ville_chantier:string;notes_chantier:string;date_devis:string;date_validite:string;conditions:string;lignes:Ligne[]};
const steps=["Client","Prestations","Détails","Récap.","Final"];
const idLigne=()=>`${Date.now()}-${Math.random().toString(36).slice(2)}`;

export default function NouveauDevisPage(){
  const navigate=useNavigate();const {profil}=useAuth();const draftKey=`arboboard-mobile-devis-${profil?.id||"inconnu"}`;
  const [step,setStep]=useState(1);const [clients,setClients]=useState<any[]>([]);const [prestations,setPrestations]=useState<any[]>([]);const [categories,setCategories]=useState<any[]>([]);
  const [clientId,setClientId]=useState("");const [rechercheClient,setRechercheClient]=useState("");const [recherchePrestation,setRecherchePrestation]=useState("");const [lignes,setLignes]=useState<Ligne[]>([]);
  const [objet,setObjet]=useState("");const [description,setDescription]=useState("");const [adresse,setAdresse]=useState("");const [cp,setCp]=useState("");const [ville,setVille]=useState("");const [notes,setNotes]=useState("");
  const [dateDevis,setDateDevis]=useState(isoAujourdHui());const [dateValidite,setDateValidite]=useState(ajouterJours(isoAujourdHui(),30));const [conditions,setConditions]=useState("");const [tvaDefaut,setTvaDefaut]=useState(20);
  const [creationClient,setCreationClient]=useState(false);const [clientRapide,setClientRapide]=useState({nom:"",prenom:"",telephone:"",email:"",adresse:"",code_postal:"",ville:""});
  const [ligneEdition,setLigneEdition]=useState<Ligne|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [devisCree,setDevisCree]=useState<any|null>(null);

  async function load(){if(!profil?.entreprise_id)return;try{setError("");const [c,cat,p,entreprise,params]=await Promise.all([
    supabase.from("clients").select("*").eq("entreprise_id",profil.entreprise_id).eq("statut","actif").order("created_at",{ascending:false}),
    supabase.from("prestations_categories").select("id,nom,actif,ordre").eq("entreprise_id",profil.entreprise_id).order("ordre",{ascending:true}),
    supabase.from("prestations_tarifs").select("id,categorie_id,code,designation,description,unite_reference,prix_vente_ht,taux_tva,actif,ordre").eq("entreprise_id",profil.entreprise_id).eq("actif",true).order("ordre",{ascending:true}).order("code",{ascending:true}),
    supabase.from("entreprises_abonnees").select("conditions_generales_devis").eq("id",profil.entreprise_id).maybeSingle(),
    supabase.from("entreprise_parametres").select("tva_defaut,conditions_generales_devis").eq("entreprise_id",profil.entreprise_id).maybeSingle()
  ]);if(c.error)throw c.error;if(cat.error)throw cat.error;if(p.error)throw p.error;setClients(c.data||[]);setCategories(cat.data||[]);setPrestations(p.data||[]);if(params.data?.tva_defaut!==null&&params.data?.tva_defaut!==undefined)setTvaDefaut(nombre(params.data.tva_defaut,20));setConditions(texte(params.data?.conditions_generales_devis,entreprise.data?.conditions_generales_devis));}catch(e){setError(e instanceof Error?e.message:"Impossible de préparer le devis.");}}
  useEffect(()=>{void load();try{const raw=localStorage.getItem(draftKey);if(raw){const d=JSON.parse(raw) as Partial<Draft>;if(d.step)setStep(Math.min(4,Math.max(1,d.step)));if(d.client_id)setClientId(d.client_id);if(d.objet!==undefined)setObjet(d.objet);if(d.description!==undefined)setDescription(d.description);if(d.adresse_chantier!==undefined)setAdresse(d.adresse_chantier);if(d.code_postal_chantier!==undefined)setCp(d.code_postal_chantier);if(d.ville_chantier!==undefined)setVille(d.ville_chantier);if(d.notes_chantier!==undefined)setNotes(d.notes_chantier);if(d.date_devis)setDateDevis(d.date_devis);if(d.date_validite)setDateValidite(d.date_validite);if(d.conditions!==undefined)setConditions(d.conditions);if(Array.isArray(d.lignes))setLignes(d.lignes);}}catch{}},[profil?.id]);
  useEffect(()=>{if(!profil?.id||devisCree)return;const d:Draft={step,client_id:clientId,objet,description,adresse_chantier:adresse,code_postal_chantier:cp,ville_chantier:ville,notes_chantier:notes,date_devis:dateDevis,date_validite:dateValidite,conditions,lignes};localStorage.setItem(draftKey,JSON.stringify(d));},[step,clientId,objet,description,adresse,cp,ville,notes,dateDevis,dateValidite,conditions,lignes,profil?.id,devisCree]);

  const client=useMemo(()=>clients.find(x=>x.id===clientId)||null,[clients,clientId]);
  const clientsFiltres=useMemo(()=>{const n=normaliser(rechercheClient);return n?clients.filter(x=>normaliser([x.nom,x.prenom,x.entreprise,x.telephone,x.email,x.ville].join(" ")).includes(n)):clients;},[clients,rechercheClient]);
  const prestationsFiltrees=useMemo(()=>{const n=normaliser(recherchePrestation);return prestations.filter(p=>{if(!n)return true;const cat=categories.find(x=>x.id===p.categorie_id);return normaliser([p.code,p.designation,p.description,cat?.nom].join(" ")).includes(n);});},[prestations,categories,recherchePrestation]);
  const totaux=useMemo(()=>{let ht=0,tva=0;for(const l of lignes){const lh=nombre(l.quantite)*nombre(l.prix_unitaire_ht);ht+=lh;tva+=lh*(nombre(l.tva)/100);}return{ht,tva,ttc:ht+tva};},[lignes]);

  function selectionnerClient(c:any){setClientId(c.id);setAdresse(texte(c.adresse_chantier,c.adresse));setCp(texte(c.code_postal_chantier,c.code_postal));setVille(texte(c.ville_chantier,c.ville));setRechercheClient("");}
  async function creerClientRapide(){if(!profil?.entreprise_id)return;if(!clientRapide.nom.trim()&&!clientRapide.prenom.trim()){setError("Renseignez le nom ou le prénom du client.");return;}try{setBusy(true);setError("");const {data,error}=await supabase.from("clients").insert({entreprise_id:profil.entreprise_id,type_client:"particulier",nom:clientRapide.nom.trim()||null,prenom:clientRapide.prenom.trim()||null,telephone:clientRapide.telephone.trim()||null,email:clientRapide.email.trim()||null,adresse:clientRapide.adresse.trim()||null,code_postal:clientRapide.code_postal.trim()||null,ville:clientRapide.ville.trim()||null,statut:"actif"}).select("*").single();if(error)throw error;setClients(old=>[data,...old]);selectionnerClient(data);setCreationClient(false);setClientRapide({nom:"",prenom:"",telephone:"",email:"",adresse:"",code_postal:"",ville:""});}catch(e){setError(e instanceof Error?e.message:"Création du client impossible.");}finally{setBusy(false);}}
  function ajouterPrestation(p:any){const l:Ligne={uid:idLigne(),prestation_id:p.id,designation:texte(p.designation,p.code,"Prestation"),description:texte(p.description),quantite:1,unite:texte(p.unite_reference,"u"),prix_unitaire_ht:nombre(p.prix_vente_ht),tva:nombre(p.taux_tva,tvaDefaut)};setLignes(old=>[...old,l]);setLigneEdition(l);}
  function ajouterLigneLibre(){const l:Ligne={uid:idLigne(),prestation_id:null,designation:"",description:"",quantite:1,unite:"u",prix_unitaire_ht:0,tva:tvaDefaut};setLignes(old=>[...old,l]);setLigneEdition(l);}
  function modifierLigne(next:Ligne){setLignes(old=>old.map(x=>x.uid===next.uid?next:x));setLigneEdition(next);}function supprimerLigne(uid:string){setLignes(old=>old.filter(x=>x.uid!==uid));setLigneEdition(null);}
  function suivant(){setError("");if(step===1&&!clientId){setError("Choisissez un client pour continuer.");return;}if(step===2&&!lignes.length){setError("Ajoutez au moins une prestation.");return;}if(step===3&&lignes.some(x=>!x.designation.trim())){setError("Chaque ligne doit avoir une désignation.");return;}setStep(s=>Math.min(5,s+1));}

  async function enregistrerDevis(){if(!profil?.entreprise_id||!client)return;if(!lignes.length||lignes.some(x=>!x.designation.trim())){setError("Le devis doit contenir au moins une ligne valide.");return;}try{setBusy(true);setError("");setMessage("");const payload={entreprise_id:profil.entreprise_id,client_id:client.id,client_nom:texte([client.prenom,client.nom].filter(Boolean).join(" "),client.entreprise,"Client"),numero:null,objet:objet.trim()||null,description:description.trim()||null,adresse_chantier:adresse.trim()||null,code_postal_chantier:cp.trim()||null,ville_chantier:ville.trim()||null,notes_chantier:notes.trim()||null,date_devis:dateDevis,date_validite:dateValidite,statut:"brouillon",total_ht:totaux.ht,total_tva:totaux.tva,total_ttc:totaux.ttc,conditions:conditions.trim()||null};const {data:devis,error:devisError}=await supabase.from("devis").insert(payload).select("id,numero,client_nom,total_ttc,statut").single();if(devisError)throw devisError;const lignesPayload=lignes.map((l,index)=>{const totalHt=nombre(l.quantite)*nombre(l.prix_unitaire_ht);const totalTva=totalHt*(nombre(l.tva)/100);return{entreprise_id:profil.entreprise_id,devis_id:devis.id,designation:l.designation.trim(),description:l.description.trim()||null,quantite:nombre(l.quantite,1),unite:l.unite||"u",prix_unitaire_ht:nombre(l.prix_unitaire_ht),tva:nombre(l.tva),total_ht:totalHt,total_tva:totalTva,total_ttc:totalHt+totalTva,ordre:index+1};});const {error:lignesError}=await supabase.from("devis_lignes").insert(lignesPayload);if(lignesError){await supabase.from("devis").delete().eq("entreprise_id",profil.entreprise_id).eq("id",devis.id);throw lignesError;}localStorage.removeItem(draftKey);setDevisCree(devis);setStep(5);setMessage("Devis créé avec succès.");}catch(e){setError(e instanceof Error?e.message:"Création du devis impossible.");}finally{setBusy(false);}}

  return <Screen title="Nouveau devis" subtitle={devisCree?"Terminé":`Étape ${step} sur 5`}>
    <ProgressSteps current={step} labels={steps}/>{error?<State type="error">{error}</State>:null}{message?<State type="success">{message}</State>:null}
    {step===1?<div className="wizard-card"><div className="wizard-heading"><p className="eyebrow">1 • CLIENT</p><h2>Pour qui est ce devis ?</h2><p>Recherchez un client existant ou créez-le sans quitter le devis.</p></div>{client?<div className="selected-client"><span className="avatar-soft">{texte(client.prenom,client.nom,client.entreprise,"C").slice(0,1).toUpperCase()}</span><div><strong>{texte([client.prenom,client.nom].filter(Boolean).join(" "),client.entreprise,"Client")}</strong><small>{texte(client.telephone,client.email,client.ville)}</small></div><button onClick={()=>setClientId("")}>Changer</button></div>:<><input className="search-input" placeholder="Rechercher un client…" value={rechercheClient} onChange={e=>setRechercheClient(e.target.value)}/><div className="pick-list">{clientsFiltres.slice(0,12).map(c=><button key={c.id} onClick={()=>selectionnerClient(c)}><span className="avatar-soft">{texte(c.prenom,c.nom,c.entreprise,"C").slice(0,1).toUpperCase()}</span><span><strong>{texte([c.prenom,c.nom].filter(Boolean).join(" "),c.entreprise,"Client")}</strong><small>{texte(c.telephone,c.email,c.ville)}</small></span><b>›</b></button>)}</div><button className="secondary tall" onClick={()=>setCreationClient(true)}>＋ Nouveau client</button></>}</div>:null}
    {step===2?<div className="wizard-card"><div className="wizard-heading"><p className="eyebrow">2 • PRESTATIONS</p><h2>Que devez-vous réaliser ?</h2><p>Tapez un mot ou un code : Arboboard retrouve vos vrais tarifs.</p></div><input className="search-input" placeholder="Ex. taille haie, élagage, broyage…" value={recherchePrestation} onChange={e=>setRecherchePrestation(e.target.value)} autoFocus/>{lignes.length?<div className="selected-lines-mini">{lignes.map(l=><button key={l.uid} onClick={()=>setLigneEdition(l)}><span>✓</span><strong>{l.designation||"Ligne libre"}</strong><b>{argent(l.quantite*l.prix_unitaire_ht)}</b></button>)}</div>:null}<div className="prestation-list">{prestationsFiltrees.slice(0,20).map(p=><button key={p.id} onClick={()=>ajouterPrestation(p)}><div><small>{texte(p.code)}</small><strong>{texte(p.designation,"Prestation")}</strong><span>{texte(p.description)}</span></div><div className="price-column"><b>{argent(p.prix_vente_ht)}</b><small>HT / {texte(p.unite_reference,"u")}</small></div></button>)}</div><button className="secondary tall" onClick={ajouterLigneLibre}>＋ Ligne libre</button></div>:null}
    {step===3?<div className="wizard-card"><div className="wizard-heading"><p className="eyebrow">3 • DÉTAILS</p><h2>Vérifiez les lignes</h2><p>Tout est modifiable. Les calculs sont automatiques.</p></div><div className="editable-lines">{lignes.map(l=><button key={l.uid} className="editable-line" onClick={()=>setLigneEdition(l)}><div><strong>{l.designation||"À compléter"}</strong><small>{l.quantite} {l.unite} × {argent(l.prix_unitaire_ht)} HT</small></div><b>{argent(l.quantite*l.prix_unitaire_ht)}</b></button>)}</div><div className="form-stack soft-panel"><label>Objet du devis <small>Facultatif</small><input placeholder="Ex. Taille et entretien des haies" value={objet} onChange={e=>setObjet(e.target.value)}/></label><label>Description générale <small>Facultatif</small><textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="form-two"><label>Date du devis<input type="date" value={dateDevis} onChange={e=>setDateDevis(e.target.value)}/></label><label>Valable jusqu’au<input type="date" value={dateValidite} onChange={e=>setDateValidite(e.target.value)}/></label></div><label>Adresse chantier<input value={adresse} onChange={e=>setAdresse(e.target.value)}/></label><div className="form-two"><label>Code postal<input value={cp} onChange={e=>setCp(e.target.value)}/></label><label>Ville<input value={ville} onChange={e=>setVille(e.target.value)}/></label></div><label>Notes chantier<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label><label>Conditions<textarea rows={4} value={conditions} onChange={e=>setConditions(e.target.value)}/></label></div></div>:null}
    {step===4?<div className="wizard-card recap-card"><div className="wizard-heading"><p className="eyebrow">4 • RÉCAPITULATIF</p><h2>Tout est prêt.</h2><p>Un dernier coup d’œil avant de créer le devis.</p></div><div className="recap-client"><small>CLIENT</small><strong>{texte([client?.prenom,client?.nom].filter(Boolean).join(" "),client?.entreprise,client?.email,"Client")}</strong><span>{[adresse,cp,ville].filter(Boolean).join(" • ")}</span></div><div className="recap-lines">{lignes.map(l=><div key={l.uid}><span><strong>{l.designation}</strong><small>{l.quantite} {l.unite}</small></span><b>{argent(l.quantite*l.prix_unitaire_ht)}</b></div>)}</div><div className="totals-card"><div><span>Total HT</span><strong>{argent(totaux.ht)}</strong></div><div><span>TVA</span><strong>{argent(totaux.tva)}</strong></div><div className="grand-total"><span>Total TTC</span><strong>{argent(totaux.ttc)}</strong></div></div><button className="primary tall" disabled={busy} onClick={()=>void enregistrerDevis()}>{busy?"Création…":"Créer le devis"}</button></div>:null}
    {step===5&&devisCree?<div className="success-final"><div className="success-ring">✓</div><p className="eyebrow">DEVIS CRÉÉ</p><h2>{texte(devisCree.numero,"Votre devis est prêt")}</h2><p>Le brouillon est enregistré dans Arboboard.</p><div className="success-total"><span>Total TTC</span><strong>{argent(devisCree.total_ttc)}</strong></div><button className="primary tall" onClick={()=>navigate("/chef/devis")}>Voir mes devis</button><button className="secondary tall" onClick={()=>window.location.reload()}>Créer un autre devis</button></div>:null}
    {step<4?<div className="wizard-bottom">{step>1?<button className="secondary" onClick={()=>setStep(s=>s-1)}>Retour</button>:null}<button className="primary" onClick={suivant}>Continuer →</button></div>:null}{step===4?<div className="wizard-back-link"><button className="text-button" onClick={()=>setStep(3)}>← Modifier le devis</button></div>:null}
    {creationClient?<div className="sheet-overlay" onClick={()=>!busy&&setCreationClient(false)}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="sheet-title-row"><div><p className="eyebrow">CLIENT RAPIDE</p><h2>Ajouter sans quitter le devis</h2></div><button className="round-button" onClick={()=>setCreationClient(false)}>×</button></div><div className="form-stack"><div className="form-two"><label>Prénom<input value={clientRapide.prenom} onChange={e=>setClientRapide({...clientRapide,prenom:e.target.value})}/></label><label>Nom<input value={clientRapide.nom} onChange={e=>setClientRapide({...clientRapide,nom:e.target.value})}/></label></div><div className="form-two"><label>Téléphone<input value={clientRapide.telephone} onChange={e=>setClientRapide({...clientRapide,telephone:e.target.value})}/></label><label>E-mail<input type="email" value={clientRapide.email} onChange={e=>setClientRapide({...clientRapide,email:e.target.value})}/></label></div><label>Adresse<input value={clientRapide.adresse} onChange={e=>setClientRapide({...clientRapide,adresse:e.target.value})}/></label><div className="form-two"><label>Code postal<input value={clientRapide.code_postal} onChange={e=>setClientRapide({...clientRapide,code_postal:e.target.value})}/></label><label>Ville<input value={clientRapide.ville} onChange={e=>setClientRapide({...clientRapide,ville:e.target.value})}/></label></div><button className="primary tall" disabled={busy} onClick={()=>void creerClientRapide()}>{busy?"Création…":"Créer et sélectionner"}</button></div></div></div>:null}
    {ligneEdition?<div className="sheet-overlay" onClick={()=>setLigneEdition(null)}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="sheet-title-row"><div><p className="eyebrow">PRESTATION</p><h2>{ligneEdition.designation||"Ligne libre"}</h2></div><button className="round-button" onClick={()=>setLigneEdition(null)}>×</button></div><div className="form-stack"><label>Désignation<input value={ligneEdition.designation} onChange={e=>modifierLigne({...ligneEdition,designation:e.target.value})}/></label><label>Description<textarea rows={3} value={ligneEdition.description} onChange={e=>modifierLigne({...ligneEdition,description:e.target.value})}/></label><div className="form-three"><label>Quantité<input type="number" min="0" step="0.01" value={ligneEdition.quantite} onChange={e=>modifierLigne({...ligneEdition,quantite:nombre(e.target.value)})}/></label><label>Unité<input value={ligneEdition.unite} onChange={e=>modifierLigne({...ligneEdition,unite:e.target.value})}/></label><label>TVA %<input type="number" value={ligneEdition.tva} onChange={e=>modifierLigne({...ligneEdition,tva:nombre(e.target.value)})}/></label></div><label>Prix unitaire HT<input type="number" min="0" step="0.01" value={ligneEdition.prix_unitaire_ht} onChange={e=>modifierLigne({...ligneEdition,prix_unitaire_ht:nombre(e.target.value)})}/></label><div className="sheet-total"><span>Total HT</span><strong>{argent(ligneEdition.quantite*ligneEdition.prix_unitaire_ht)}</strong></div><button className="primary tall" onClick={()=>setLigneEdition(null)}>Ajouter au devis</button><button className="danger-link" onClick={()=>supprimerLigne(ligneEdition.uid)}>Supprimer cette ligne</button></div></div></div>:null}
  </Screen>;
}
